### ISSUE TITLE
Add support for "use_thread" property for all modules

### ISSUE THREAD

**Issue by alushnikov** [nuigroup/ccv2#15]
Currently "use_thread" : "true" property works for only a few modules and mostly in conjunction with "oscillator" property set to "true". Need fix for that.

**Comment by shalstvedt** [comment]
This works right for filters and sinks.

For sources/cameras, oscillator_mode sets up a thread.  use_thread for some reason breaks this, so we either have to fix that or perhaps take this opportunity to make the naming clearer.  Perhaps, "mode" : ["oscillator" | "threaded" | "synchronized"]?

Also, as of now, "use_thread" : "true" must be combined with async mode (independently threaded) endpoints on some modules. I'll post back with a list.
